### PR TITLE
hacktoberfest2022

### PR DESCRIPTION
**Pull request by raj-hero**
@Visheshrwl I did the following things=>
- created about.html and about.css which contains information about you and also contains a text animation
- added favicon to index.html, about.html and contact.html. favicon.png uploaded to img folder
- modified contact.html only for favicon in <head>
- modified  index.html only for favicon in <head> and linking about.html
- modified mobile.css only in class="home-article-content" for text animation
No other changes are made
Do add hacktoberfest-accepted tag if no issues are found

### CODE REVIEW

**Comment by Visheshrwl** [comment]
#2 #hacktoberfest-accepted

**Comment by Visheshrwl** [comment]
please create a new pull request with these changes

**Comment by raj-hero** [comment]
> please create a new pull request with these changes

@Visheshrwl , the same changes a s done before, or some bug was present?

**Comment by raj-hero** [comment]
> > please create a new pull request with these changes
> 
> @Visheshrwl , the same changes as done before, or some other changes other than my coomits in PR #2

**Comment by Visheshrwl** [comment]
the same changes please. Thanks :)

**Comment by raj-hero** [comment]
> the same changes please. Thanks :)
ok

**Comment by raj-hero** [comment]
@Visheshrwl see PR #5 and mention the issues, if found any.

**Comment by raj-hero** [comment]
> the same changes please. Thanks :)
@Visheshrwl see PR https://github.com/Visheshrwl/Visheshrwl/pull/5 and mention the issues, if found any.

**Pull request merged**
